// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_web1.Models;

#nullable disable

namespace project_web1.Migrations
{
    [DbContext(typeof(TrungTamTreContext))]
    partial class TrungTamTreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.CtchiTieu", b =>
                {
                    b.Property<int>("MaPhieuChiTieu")
                        .HasColumnType("int");

                    b.Property<int>("ChiTieuId")
                        .HasColumnType("int")
                        .HasColumnName("ChiTieuID");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("MaPhieuChiTieu", "ChiTieuId")
                        .HasName("PK__CTChiTie__98E08775690AB346");

                    b.HasIndex("ChiTieuId");

                    b.ToTable("CTChiTieu", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.Ctdonthuoc", b =>
                {
                    b.Property<int>("MaDonThuoc")
                        .HasColumnType("int");

                    b.Property<int>("MaSoThuoc")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaDonThuoc", "MaSoThuoc")
                        .HasName("PK__CTDonthu__211B1A7D825BA313");

                    b.HasIndex("MaSoThuoc");

                    b.ToTable("CTDonthuoc", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.CtphieuMua", b =>
                {
                    b.Property<int>("MaSoThuoc")
                        .HasColumnType("int");

                    b.Property<int>("MaSoMuaThuoc")
                        .HasColumnType("int");

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaSoThuoc", "MaSoMuaThuoc")
                        .HasName("PK__CTPhieuM__B00654CE229F77BA");

                    b.HasIndex("MaSoMuaThuoc");

                    b.ToTable("CTPhieuMua", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.DonThuoc", b =>
                {
                    b.Property<int>("MaDonThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonThuoc"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("MaSoTre")
                        .HasColumnType("int");

                    b.Property<string>("ThoiGianDung")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaDonThuoc")
                        .HasName("PK__DonThuoc__3EF99EE1EE7B2347");

                    b.HasIndex("MaSoTre");

                    b.ToTable("DonThuoc", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("project_web1.Models.HoSoSucKhoe", b =>
                {
                    b.Property<int>("MaHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSo"));

                    b.Property<double?>("CanNang")
                        .HasColumnType("float");

                    b.Property<double?>("ChieuCao")
                        .HasColumnType("float");

                    b.Property<string>("DiUng")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("Idnvyte")
                        .HasColumnType("int")
                        .HasColumnName("IDNVYTe");

                    b.Property<string>("KetLuan")
                        .HasColumnType("text");

                    b.Property<int>("MaSoTre")
                        .HasColumnType("int");

                    b.Property<string>("TienSuBenh")
                        .HasColumnType("text");

                    b.Property<string>("TinhTrangSucKhoe")
                        .HasColumnType("text");

                    b.HasKey("MaHoSo")
                        .HasName("PK__HoSoSucK__1666423CE1228521");

                    b.HasIndex("Idnvyte");

                    b.HasIndex("MaSoTre");

                    b.ToTable("HoSoSucKhoe", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.HoaDonTaiTro", b =>
                {
                    b.Property<int>("MaSoPhieuHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSoPhieuHoaDon"));

                    b.Property<int>("MaSoNtt")
                        .HasColumnType("int")
                        .HasColumnName("MaSoNTT");

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("MaSoPhieuHoaDon")
                        .HasName("PK__HoaDonTa__A3C734FB6D0262A1");

                    b.HasIndex("MaSoNtt");

                    b.ToTable("HoaDonTaiTro", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.LoaiChiTieu", b =>
                {
                    b.Property<int>("ChiTieuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChiTieuID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTieuId"));

                    b.Property<string>("TenChiTieu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChiTieuId")
                        .HasName("PK__LoaiChiT__BF79296D3B799B76");

                    b.ToTable("LoaiChiTieu", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.NguoiChamSoc", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NguoiCha__77B2CA47B0F11B58");

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiCha__A9D105343FA2E38B")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("NguoiChamSoc", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.NguoiNhanNuoi", b =>
                {
                    b.Property<int>("MaSoNnn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSoNNN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSoNnn"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MaSoTre")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.HasKey("MaSoNnn")
                        .HasName("PK__NguoiNha__7CDA1DBCBC4BEC9C");

                    b.HasIndex("MaSoTre");

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiNha__A9D1053421154CDA")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("NguoiNhanNuoi", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.NhaTaiTro", b =>
                {
                    b.Property<int>("MaSoNtt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSoNTT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSoNtt"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("")
                        .HasColumnName("SDT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("");

                    b.Property<string>("ToChuc")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaSoNtt")
                        .HasName("PK__NhaTaiTr__7CDA6C8EAFF0EB15");

                    b.ToTable("NhaTaiTro", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.NhanVienYte", b =>
                {
                    b.Property<int>("Idnvyte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNVYTe");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idnvyte"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DonVi")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Loai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Idnvyte")
                        .HasName("PK__NhanVien__CAEFD41E4F0E7121");

                    b.ToTable("NhanVienYTe", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.PhieuChiTieu", b =>
                {
                    b.Property<int>("MaPhieuChiTieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuChiTieu"));

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayGhi")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("MaPhieuChiTieu")
                        .HasName("PK__PhieuChi__531715E38175541F");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PhieuChiTieu", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.PhieuKhamBenh", b =>
                {
                    b.Property<int>("MaPhieuKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuKham"));

                    b.Property<double?>("CanNang")
                        .HasColumnType("float");

                    b.Property<double?>("ChieuCao")
                        .HasColumnType("float");

                    b.Property<int>("Idnvyte")
                        .HasColumnType("int")
                        .HasColumnName("IDNVYTe");

                    b.Property<int>("MaSoTre")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGhi")
                        .HasColumnType("datetime");

                    b.Property<string>("TinhTrangSucKhoe")
                        .HasColumnType("text");

                    b.HasKey("MaPhieuKham")
                        .HasName("PK__PhieuKha__FACA55DF6919B3EC");

                    b.HasIndex("Idnvyte");

                    b.HasIndex("MaSoTre");

                    b.ToTable("PhieuKhamBenh", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.PhieuTiemChung", b =>
                {
                    b.Property<int>("MaSoTiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSoTiem"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("MaSoTre")
                        .HasColumnType("int");

                    b.Property<int>("MaSoVaccine")
                        .HasColumnType("int");

                    b.Property<byte?>("MuiThu")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("NgayTiem")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaSoTiem")
                        .HasName("PK__PhieuTie__1E41A5178A59F172");

                    b.HasIndex(new[] { "MuiThu" }, "UQ__PhieuTie__02D60CDD47617401")
                        .IsUnique()
                        .HasFilter("[MuiThu] IS NOT NULL");

                    b.HasIndex(new[] { "MaSoTre" }, "UQ__PhieuTie__712406C9CEAADAB5")
                        .IsUnique();

                    b.HasIndex(new[] { "MaSoVaccine" }, "UQ__PhieuTie__B7D083B06E18FB0F")
                        .IsUnique();

                    b.ToTable("PhieuTiemChung", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.Thuoc", b =>
                {
                    b.Property<int>("MaSoThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSoThuoc"));

                    b.Property<string>("CongDung")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("HoatChat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LieuLuongDeXuat")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaSoThuoc")
                        .HasName("PK__Thuoc__FE2849C0D63FCA19");

                    b.ToTable("Thuoc", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.ThuocMuaNgoai", b =>
                {
                    b.Property<int>("MaSoMuaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSoMuaThuoc"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayMua")
                        .HasColumnType("datetime");

                    b.Property<string>("NoiMua")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("MaSoMuaThuoc")
                        .HasName("PK__ThuocMua__E2E1D0E582AD8A7D");

                    b.ToTable("ThuocMuaNgoai", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.Tre", b =>
                {
                    b.Property<int>("MaSoTre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSoTre"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayNhapTrungTam")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime");

                    b.Property<string>("Quote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("quote");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaSoTre")
                        .HasName("PK__Tre__712406C85A2E070B");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("Tre", (string)null);
                });

            modelBuilder.Entity("project_web1.Models.Vaccine", b =>
                {
                    b.Property<int>("MaSoVaccine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSoVaccine"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime");

                    b.Property<string>("PhongBenh")
                        .HasColumnType("text");

                    b.Property<byte?>("SoMuiCanTiem")
                        .HasColumnType("tinyint");

                    b.Property<string>("TenVaccine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaSoVaccine")
                        .HasName("PK__Vaccine__B7D083B14B33D524");

                    b.ToTable("Vaccine", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("project_web1.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("project_web1.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_web1.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("project_web1.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("project_web1.Models.CtchiTieu", b =>
                {
                    b.HasOne("project_web1.Models.LoaiChiTieu", "ChiTieu")
                        .WithMany("CtchiTieus")
                        .HasForeignKey("ChiTieuId")
                        .IsRequired()
                        .HasConstraintName("FK__CTChiTieu__ChiTi__6C190EBB");

                    b.HasOne("project_web1.Models.PhieuChiTieu", "MaPhieuChiTieuNavigation")
                        .WithMany("CtchiTieus")
                        .HasForeignKey("MaPhieuChiTieu")
                        .IsRequired()
                        .HasConstraintName("FK__CTChiTieu__MaPhi__6B24EA82");

                    b.Navigation("ChiTieu");

                    b.Navigation("MaPhieuChiTieuNavigation");
                });

            modelBuilder.Entity("project_web1.Models.Ctdonthuoc", b =>
                {
                    b.HasOne("project_web1.Models.DonThuoc", "MaDonThuocNavigation")
                        .WithMany("Ctdonthuocs")
                        .HasForeignKey("MaDonThuoc")
                        .IsRequired()
                        .HasConstraintName("FK__CTDonthuo__MaDon__6A30C649");

                    b.HasOne("project_web1.Models.Thuoc", "MaSoThuocNavigation")
                        .WithMany("Ctdonthuocs")
                        .HasForeignKey("MaSoThuoc")
                        .IsRequired()
                        .HasConstraintName("FK__CTDonthuo__MaSoT__5CD6CB2B");

                    b.Navigation("MaDonThuocNavigation");

                    b.Navigation("MaSoThuocNavigation");
                });

            modelBuilder.Entity("project_web1.Models.CtphieuMua", b =>
                {
                    b.HasOne("project_web1.Models.ThuocMuaNgoai", "MaSoMuaThuocNavigation")
                        .WithMany("CtphieuMuas")
                        .HasForeignKey("MaSoMuaThuoc")
                        .IsRequired()
                        .HasConstraintName("FK__CTPhieuMu__MaSoM__693CA210");

                    b.HasOne("project_web1.Models.Thuoc", "MaSoThuocNavigation")
                        .WithMany("CtphieuMuas")
                        .HasForeignKey("MaSoThuoc")
                        .IsRequired()
                        .HasConstraintName("FK__CTPhieuMu__MaSoT__5DCAEF64");

                    b.Navigation("MaSoMuaThuocNavigation");

                    b.Navigation("MaSoThuocNavigation");
                });

            modelBuilder.Entity("project_web1.Models.DonThuoc", b =>
                {
                    b.HasOne("project_web1.Models.Tre", "MaSoTreNavigation")
                        .WithMany("DonThuocs")
                        .HasForeignKey("MaSoTre")
                        .IsRequired()
                        .HasConstraintName("FK__DonThuoc__MaSoTr__6477ECF3");

                    b.Navigation("MaSoTreNavigation");
                });

            modelBuilder.Entity("project_web1.Models.HoSoSucKhoe", b =>
                {
                    b.HasOne("project_web1.Models.NhanVienYte", "IdnvyteNavigation")
                        .WithMany("HoSoSucKhoes")
                        .HasForeignKey("Idnvyte")
                        .IsRequired()
                        .HasConstraintName("FK__HoSoSucKh__IDNVY__68487DD7");

                    b.HasOne("project_web1.Models.Tre", "MaSoTreNavigation")
                        .WithMany("HoSoSucKhoes")
                        .HasForeignKey("MaSoTre")
                        .IsRequired()
                        .HasConstraintName("FK__HoSoSucKh__MaSoT__656C112C");

                    b.Navigation("IdnvyteNavigation");

                    b.Navigation("MaSoTreNavigation");
                });

            modelBuilder.Entity("project_web1.Models.HoaDonTaiTro", b =>
                {
                    b.HasOne("project_web1.Models.NhaTaiTro", "MaSoNttNavigation")
                        .WithMany("HoaDonTaiTros")
                        .HasForeignKey("MaSoNtt")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDonTai__MaSoN__66603565");

                    b.Navigation("MaSoNttNavigation");
                });

            modelBuilder.Entity("project_web1.Models.NguoiNhanNuoi", b =>
                {
                    b.HasOne("project_web1.Models.Tre", "MaSoTreNavigation")
                        .WithMany("NguoiNhanNuois")
                        .HasForeignKey("MaSoTre")
                        .IsRequired()
                        .HasConstraintName("FK__NguoiNhan__MaSoT__6383C8BA");

                    b.Navigation("MaSoTreNavigation");
                });

            modelBuilder.Entity("project_web1.Models.PhieuChiTieu", b =>
                {
                    b.HasOne("project_web1.Models.NguoiChamSoc", "MaNhanVienNavigation")
                        .WithMany("PhieuChiTieus")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuChiT__MaNha__60A75C0F");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("project_web1.Models.PhieuKhamBenh", b =>
                {
                    b.HasOne("project_web1.Models.NhanVienYte", "IdnvyteNavigation")
                        .WithMany("PhieuKhamBenhs")
                        .HasForeignKey("Idnvyte")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuKham__IDNVY__6754599E");

                    b.HasOne("project_web1.Models.Tre", "MaSoTreNavigation")
                        .WithMany("PhieuKhamBenhs")
                        .HasForeignKey("MaSoTre")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuKham__MaSoT__619B8048");

                    b.Navigation("IdnvyteNavigation");

                    b.Navigation("MaSoTreNavigation");
                });

            modelBuilder.Entity("project_web1.Models.PhieuTiemChung", b =>
                {
                    b.HasOne("project_web1.Models.Tre", "MaSoTreNavigation")
                        .WithOne("PhieuTiemChung")
                        .HasForeignKey("project_web1.Models.PhieuTiemChung", "MaSoTre")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuTiem__MaSoT__628FA481");

                    b.HasOne("project_web1.Models.Vaccine", "MaSoVaccineNavigation")
                        .WithOne("PhieuTiemChung")
                        .HasForeignKey("project_web1.Models.PhieuTiemChung", "MaSoVaccine")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuTiem__MaSoV__5EBF139D");

                    b.Navigation("MaSoTreNavigation");

                    b.Navigation("MaSoVaccineNavigation");
                });

            modelBuilder.Entity("project_web1.Models.Tre", b =>
                {
                    b.HasOne("project_web1.Models.NguoiChamSoc", "MaNhanVienNavigation")
                        .WithMany("Tres")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK__Tre__MaNhanVien__5FB337D6");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("project_web1.Models.DonThuoc", b =>
                {
                    b.Navigation("Ctdonthuocs");
                });

            modelBuilder.Entity("project_web1.Models.LoaiChiTieu", b =>
                {
                    b.Navigation("CtchiTieus");
                });

            modelBuilder.Entity("project_web1.Models.NguoiChamSoc", b =>
                {
                    b.Navigation("PhieuChiTieus");

                    b.Navigation("Tres");
                });

            modelBuilder.Entity("project_web1.Models.NhaTaiTro", b =>
                {
                    b.Navigation("HoaDonTaiTros");
                });

            modelBuilder.Entity("project_web1.Models.NhanVienYte", b =>
                {
                    b.Navigation("HoSoSucKhoes");

                    b.Navigation("PhieuKhamBenhs");
                });

            modelBuilder.Entity("project_web1.Models.PhieuChiTieu", b =>
                {
                    b.Navigation("CtchiTieus");
                });

            modelBuilder.Entity("project_web1.Models.Thuoc", b =>
                {
                    b.Navigation("Ctdonthuocs");

                    b.Navigation("CtphieuMuas");
                });

            modelBuilder.Entity("project_web1.Models.ThuocMuaNgoai", b =>
                {
                    b.Navigation("CtphieuMuas");
                });

            modelBuilder.Entity("project_web1.Models.Tre", b =>
                {
                    b.Navigation("DonThuocs");

                    b.Navigation("HoSoSucKhoes");

                    b.Navigation("NguoiNhanNuois");

                    b.Navigation("PhieuKhamBenhs");

                    b.Navigation("PhieuTiemChung");
                });

            modelBuilder.Entity("project_web1.Models.Vaccine", b =>
                {
                    b.Navigation("PhieuTiemChung");
                });
#pragma warning restore 612, 618
        }
    }
}
